config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#home'
  get '/app', to: 'static_pages#app'
  get resources :childrens
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/center.rb
class Center < ApplicationRecord
  has_many :teachers, class_name: "User"
  has_many :children, class_name: "Child"
end

app/models/child.rb
class Child < ApplicationRecord

  belongs_to :center, optional: true
    has_many :teacher_children, inverse_of: :child
    has_many :teachers, through: :teacher_children, source: :user
end

app/models/routine.rb
class Routine < ApplicationRecord
  belongs_to :child
end

app/models/sleep.rb
class Sleep < ApplicationRecord
  belongs_to :child
end

app/models/teacher_child.rb
class TeacherChild < ApplicationRecord
  belongs_to :user, inverse_of: :teacher_children, optional: true
  belongs_to :child, inverse_of: :teacher_children, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :center, optional: true    
  has_many :teacher_children, inverse_of: :user
  has_many :children, through: :teacher_children

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/childrens_controller.rb
class ChildrensController < ApplicationController
  skip_before_action :verify_authenticity_token, if: Proc.new{:json_request?}
  def index
    @kids = Child.all
    render json: @kids
  end 

  def create
    @kid = Child.create(kid_params)
    if @kid.save
      render json: @kid
    else 
      render json: {error: @kid.errors.messages}, status: 400
    end  
  end 

  private
    def kid_params
      params.permit(:name, :lastname)
    end

    def json_request?
      request.format.json?
    end 
end

app/controllers/childs_controller.rb
class ChildsController < ApplicationController
  skip_before_action :verify_authenticity_token, if: Proc.new{:json_request?}
  def index
    @kids = Child.all
    render json: @kids
  end 

  def create
    @kid = Child.create(kid_params)
    if @kid.save
      render json: @kid
    else 
      render json: {error: @kid.errors.messages}, status: 400
    end  
  end 

  private
    def kid_params
      params.permit(:name, :lastname)
    end

    def json_request?
      request.format.json?
    end 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def app

  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/childrens_helper.rb
module ChildrensHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_head_tags.html.erb
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_navbar.html.erb
<nav class="navbar is-info" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="https://bulma.io">
        <img src="https://bulma.io/images/bulma-logo.png" alt="Bulma: a modern CSS framework based on Flexbox" width="112" height="28">
      </a>
      <div class="navbar-burger" data-target="navMenu">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
    <div class="navbar-menu" id="navMenu">
      <div class="navbar-end">
        <%= link_to "App", app_path, class: "navbar-item", 'data-turbolinks' => false%>
        <%= link_to "Home", root_path, class: "navbar-item"%>
        <%= link_to "Contact", "/", class: "navbar-item"%>
      </div>  
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecetasker</title>
    <%=render 'layouts/head_tags'%>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/static_pages/app.html.erb
<div class="app"><%= javascript_pack_tag 'application' %></div>

<%= stylesheet_pack_tag 'application' %>

app/views/static_pages/home.html.erb
  <section class="hero is-info is-medium">
    <div class="hero-body">
      <div class="container has-text-centered">
        <h1 class="title">
          <%= link_to "Click here to Register", new_user_registration_path %>
        </h1>
        <h2 class="subtitle">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        </h2>
      </div>
    </div>
  </section>
  <section>
    <div class="container">
      <div class="columns features">
          <div class="column is-4">
            <div class="card">
              <div class="card-image has-text-centered">
                  <i class="fa fa-paw"></i>
              </div>
              <div class="card-content">
                <div class="content">
                  <h4>Tristique senectus et netus et. </h4>
                  <p>Purus semper eget duis at tellus at urna condimentum mattis. Non blandit massa enim nec. Integer enim neque volutpat ac tincidunt vitae semper quis. Accumsan tortor posuere ac ut consequat semper viverra nam.</p>
                  <p><a href="#">Learn more</a></p>
                </div>
              </div>
            </div>
          </div>
          <div class="column is-4">
            <div class="card">
              <div class="card-image has-text-centered">
                  <i class="fa fa-id-card-o"></i>
              </div>
              <div class="card-content">
                <div class="content">
                  <h4>Tempor orci dapibus ultrices in.</h4>
                  <p>Ut venenatis tellus in metus vulputate. Amet consectetur adipiscing elit pellentesque. Sed arcu non odio euismod lacinia at quis risus. Faucibus turpis in eu mi bibendum neque egestas cmonsu songue. Phasellus vestibulum</p>
                  <p><a href="#">Learn more</a></p>
                </div>
              </div>
            </div>
          </div>
          <div class="column is-4">
            <div class="card">
              <div class="card-image has-text-centered">
                  <i class="fa fa-rocket"></i>
              </div>
              <div class="card-content">
                <div class="content">
                  <h4> Leo integer malesuada nunc vel risus.  </h4>
                  <p>Imperdiet dui accumsan sit amet nulla facilisi morbi. Fusce ut placerat orci nulla pellentesque dignissim enim. Libero id faucibus nisl tincidunt eget nullam. Commodo viverra maecenas accumsan </p>
                  <p><a href="#">Learn more</a></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>  